# -*- coding: utf-8 -*-
# Generated by Django file and filefolder.11.11 on 2018-05-24 13:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initWeb', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Job',
        ),
    ]
